server:
  port: 8001
spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #当前数据库操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver #jdbc mysql驱动
    url: jdbc:mysql://localhost:3306/fruits?useUnicode=true&characterEncoding=utf-8&useSSL=false  #jdbc  url
    username: root
    password: mysqlZhenyu0711


mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.springcloud.entities //所有entities所在的包